# Generated by Django 2.2.1 on 2019-05-28 23:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190526_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('geojson', jsonfield.fields.JSONField()),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Provider')),
            ],
        ),
    ]
